package com.hybridchat.app;

/**
 * BuildConfig - Auto-generated build configuration
 * 
 * This file is normally auto-generated by the Android build system.
 * For manual builds, this stub provides the DEBUG flag.
 */
public final class BuildConfig {
    public static final boolean DEBUG = true;
    public static final String APPLICATION_ID = "com.hybridchat.app";
    public static final String BUILD_TYPE = "debug";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
}
